title: Lance Inimgba # your name (or website title) here
logo: "/images/ProPic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data science enthusiast who loves getting lost in Jupyter notebooks 😋 <br> 
  Love travel and foodie actvities! <br><br>
  <a href="https://www.linkedin.com/in/lance-inimgba-65a23a50/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
